    const Page = () => {
        return (
            <>
                <h2 className="mt-10 text-2xl font-bold">Effective Date: June 5, 2024</h2>
                <h2 className="text-2xl font-bold">Last Updated: June 5, 2024</h2>

                <p className="text-base">Please read these Terms & Conditions ("Terms") carefully before using Promp2.io ("we," "us," or "our") website and services (collectively, the "Services"). By using our Services, you agree to be bound by these Terms. If you do not agree to these Terms, you may not use our Services.</p>

                <h3 className="text-lg font-bold mt-4">1. Account Creation and Use</h3>

                <p className="text-base">1.1. To use our Services, you must create an account by logging in through your Google, Facebook, or GitHub account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.</p>

                <p className="text-base">1.2. You agree to provide accurate and complete information when creating your account and to update your information as needed to keep it accurate and complete.</p>

                <p className="text-base">1.3. We reserve the right to suspend or terminate your account at any time for any reason, including if you violate these Terms.</p>

                <h3 className="text-lg font-bold mt-4">2. Use of Our Services</h3>

                <p className="text-base">2.1. You may use our Services only for lawful purposes and in accordance with these Terms. You may not use our Services in any way that violates any applicable federal, state, local, or international law or regulation.</p>

                <p className="text-base">2.2. You may not use our Services to create or generate any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable.</p>

                <p className="text-base">2.3. You may not use our Services to impersonate any person or entity or to falsely state or otherwise misrepresent your affiliation with a person or entity.</p>

                <p className="text-base">2.4. You may not use our Services to interfere with or disrupt the integrity or performance of our Services or the data contained therein.</p>

                <h3 className="text-lg font-bold mt-4">3. Intellectual Property</h3>

                <p className="text-base">3.1. All content included on our Services, such as text, graphics, logos, images, data compilations, and software, is the property of Promp2.io or its licensors and is protected by copyright and other intellectual property laws.</p>

                <p className="text-base">3.2. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on our Services.</p>

                <p className="text-base">3.3. By submitting content to our Services, you grant us a non-exclusive, worldwide, royalty-free, perpetual, irrevocable, sublicensable, and transferable license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content in any media.</p>

                <h3 className="text-lg font-bold mt-4">4. Disclaimers</h3>

                <p className="text-base">4.1. Our Services are provided "as is" and without warranties of any kind, either express or implied. We disclaim all warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.</p>

                <p className="text-base">4.2. We do not warrant that our Services will be uninterrupted, error-free, or secure.</p>

                <p className="text-base">4.3. We are not responsible for any content generated by our Services. You are solely responsible for the accuracy, completeness, and appropriateness of any content you create or generate using our Services.</p>

                <h3 className="text-lg font-bold mt-4">5. Limitation of Liability</h3>

                <p className="text-base">5.1. In no event shall Promp2.io, its affiliates, or their respective officers, directors, employees, agents, licensors, or service providers be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses, resulting from the use or inability to use our Services.</p>

                <h3 className="text-lg font-bold mt-4">6. Indemnification</h3>

                <p className="text-base">You agree to indemnify, defend, and hold harmless Promp2.io, its affiliates, and their respective officers, directors, employees, agents, licensors, and service providers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of our Services.</p>

                <h3 className="text-lg font-bold mt-4">7. Governing Law and Dispute Resolution</h3>

                <p className="text-base">These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction]. Any dispute arising out of or relating to these Terms or the use of our Services shall be resolved exclusively in the state or federal courts located in [Your Jurisdiction].</p>

                <h3 className="text-lg font-bold mt-4">8. Changes to These Terms</h3>

                <p className="text-base">We may update these Terms from time to time. If we make any material changes, we will notify you by email or through a notice on our website.</p>

                <h3 className="text-lg font-bold mt-4">9. Contact Us</h3>

                <p className="text-base">If you have any questions about these Terms, please contact us at [email protected]</p>

                <p className="text-base">By using our Services, you acknowledge that you have read and understood these Terms and agree to be bound by them.</p>
            </>
        );
    }

    export default Page;